import { HttpStatus } from '@nestjs/common';

export const StatusCodeEnum = {
  ...HttpStatus,
  ALREADY_EXIST: 600,
  INVALID_PASSWORD: 601,
  MISSING_JWT_SECRET: 602,
  BAD_CREDENTIALS: 603,
  ALREADY_VERIFIED: 604,
  INVALID_VERIFICATION_CODE: 605,
  COMPANY_NOT_FOUND: 606,
  COMPANY_USER_NOT_FOUND: 607,
  MOCK_NOT_FOUND: 608,
  JOB_NOT_FOUND: 609,
  MOCK_IN_USE: 610,
  CANDIDATE_NOT_FOUND: 611,
  PERFORMANCE_ALREADY_EXISTS: 612,
  CV_ANALYSIS_ALREADY_EXISTS: 613,
  PERFORMANCE_NOT_FOUND: 614,
  VIDEO_NOT_FOUND: 615,
};
